# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OmiSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'OmiKit', '~>1.5.35'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 5.0'
  use_frameworks!

  # Pods for OmiSwiftUI

end
